HTTP/2 200 
server: Tengine
content-type: application/zip
content-length: 3301220
date: Tue, 04 Aug 2026 05:49:05 GMT
x-oss-request-id: 6A717D5101FFF7333140654B
x-oss-cdn-auth: success
accept-ranges: bytes
x-oss-object-type: Normal
x-oss-storage-class: Standard
etag: "B974B4299F7CEB2C28E67F9EAF594D42"
last-modified: Mon, 03 Aug 2026 07:50:10 GMT
x-oss-hash-crc64ecma: 6170833635671241691
content-md5: uXS0KZ986ywo5n+er1lNQg==
x-oss-server-time: 33
via: ens-cache31.l2us5[315,324,200-0,H], ens-cache6.l2us5[326,0], ens-cache9.us33[1122,1122,200-0,M], ens-cache2.us33[1137,0]
age: 0
ali-swift-global-savetime: 1785822545
x-cache: MISS TCP_MISS dirn:-2:-2
x-swift-savetime: Tue, 04 Aug 2026 05:49:05 GMT
x-swift-cachetime: 3600
timing-allow-origin: *
eagleid: a3b5f69617858225445596688e

